### PR TITLE
bugfix/empty_tip_root

### LINKED ISSUE #9: Improper handling of empty `tip` and `root` strings in `InverseDynamicsSolverKDL`
**Description**
There is a minor bug that occurs when empty strings are passed to the `root` and `tip` parameters of the `kdl_inverse_dynamics_solver/InverseDynamicsSolverKDL` plugin.

**Steps to reproduce**
For the `Humble` distro, load the plugin `kdl_inverse_dynamics_solver/InverseDynamicsSolverKDL` and set the following node parameters:
```yaml
tip: ""
root: ""
```
Then, the following message arises from the exception thrown by the IDS:
```shell
Failed to find chain from robot root  to end-effector .
```

**Expected Behavior**
- The IDS should be able to handle an empty string for the root parameter gracefully.

- When an empty string is passed for the tip, the following exception is expected:
```shell
Failed to find parameter 'tip'.
```

### PR DESCRIPTION
**Pull request by v8p1197**
Closes #9.

### CODE REVIEW

File: kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp [hunk 1]
```diff
@@ -66,25 +66,29 @@ void InverseDynamicsSolverKDL::initialize(rclcpp::node_interfaces::NodeParameter
   // Get root name
   rclcpp::Parameter root_param = rclcpp::Parameter();
   std::string root;
-  if (parameters_interface->has_parameter(ns + "root"))
+  bool root_found = parameters_interface->has_parameter(ns + "root");
+  if (root_found)
   {
     parameters_interface->get_parameter(ns + "root", root_param);
     root = root_param.as_string();
+    root_found = !root.empty();
```
Comment (eferre89) [inline kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp]: In my opinion, the case "the user provides an empty `root` parameter" and the case "the user does not provide a `root` parameter" are very different, and should be handled differently. Indeed, in the former case, the user knows that a `root` parameter is required, but they provide the empty string on purpose. In this case, the class shall not assume that the user wants to use the chain's root segment. For example, in developing an application, the user might want to decide the root later on, "stubbing" it to `""` temporarily. In the latter case, either the user does not know that a root parameter is required (in this case, assuming the root segment sounds reasonable) or they know that the application will use the root segment by default.

File: kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp [hunk 2]
```diff
@@ -66,25 +66,29 @@ void InverseDynamicsSolverKDL::initialize(rclcpp::node_interfaces::NodeParameter
...
+  if (tip_found)
   {
     parameters_interface->get_parameter(ns + "tip", tip_param);
     tip = tip_param.as_string();
+    tip_found = !tip.empty();
   }
-  else
+  if (!tip_found)
   {
     throw inverse_dynamics_solver::ParameterUninitializedException("Failed to find parameter 'tip'.");
```
Comment (eferre89) [inline kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp]: This exception message does not match the actual error condition: we are telling the user that the parameter `tip` does not exist, while it might be empty. The two conditions shall be handled separately.

**Review by eferre89 — CHANGES_REQUESTED** [review]

File: kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp (hunk 1 above)
Comment (v8p1197) [reply kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp]: Ok, the scenarios you are describing are intriguing and sound reasonable.

To correctly implement them, the class should expose an interface to reconfigure the filter (or, at least, the root link parameter), to support the "set the root link later on" use case.
Do you agree with this choice?
Shall I implement this?

File: kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp (hunk 2 above)
Comment (v8p1197) [reply kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp]: That's fair. I'll do that.

File: kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp (hunk 1 above)
Comment (v8p1197) [reply kdl_inverse_dynamics_solver/src/kdl_inverse_dynamics_solver.cpp]: In an internal meeting, we agreed to just log different messages, to warn the user about the usage of this module via either warnings or exceptions.

**Review by eferre89 — APPROVED** [review]
